title: <p align="center"> Laxmi kant Mishra </p>
logo: /assets/img/1652198613610.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/iamlaxmikant">LinkedIn</a> |
  <a href="https://github.com/laxmikantmishra">GitHub</a>
  
  <br> 
 Full Stack Developer | Microsoft Azure | .Net Core | Angular | Python | MS Dynamics 365 | Global Tax Platform | EY GDS
 
- 10+ years of experience in Software development focusing in Analysis, Object Oriented Design, Development, Deployment, Testing, Documentation and Maintenance in a web based environment, Distributed n-tier architecture and Client Server architecture.
- Specialized in Dotnet ecosystem, C#, Python, Azure, Microservice, AKS, WPF, Web application, SQL Server, WCF, jQuery/JavaScript, Angular, Typescript, LINQ/Lambda Expression.
- Work Experience includes designing and developing of object oriented software applications with a wide exposure to E-Commerce and Business Automation (Insurance Inspection and Premium Audit).
<br>
  </p>



theme: jekyll-theme-minimal
