title: <p align="center"> Laxmi kant Mishra </p>
logo: /assets/img/1652198613610.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/iamlaxmikant">LinkedIn</a> |
  <a href="https://github.com/laxmikantmishra">GitHub</a>
  
  <br> 
  Full Stack Developer | Microsoft Azure | .Net Core | Angular | Python | MS Dynamics 365 | Global Tax Platform | EY GDS
  <b>	10+ years of experience in Software development focusing in Analysis, Object Oriented Design, Development, Deployment, Testing, Documentation and Maintenance in a web based environment, Distributed n-tier architecture and Client Server architecture.
  </b><b>	Specialized in Dotnet ecosystem, C#, Python, Azure, Microservice, AKS, WPF, Web application, SQL Server, WCF, jQuery/JavaScript, Angular, Typescript, LINQ/Lambda Expression.
  </b><b>	Hands on Kendo UI, Web API and Elmah(Open source library for Error handling)
  </b><b>	Work Experience includes designing and developing of object oriented software applications with a wide exposure to E-Commerce and Business Automation (Insurance Inspection and Premium Audit).
  </b><b>	Having good command over Design Pattern (Repository Pattern) with Unit of Work. Hands on experience in Observer Patter and Repository.
  </b><b> Developed Mobile App using Xamarin to take Photos and sync with server.
  </b><b>	Worked on SQL Server and SQL Lite.
  </b><b>	Knowledge on Web API, WCF, and Web Services.
  </b><b>	Hands on experience on PDF (Static, Editable) generation using PDFSharp and O2 Solution tool..
  <br>
  </p>



theme: jekyll-theme-minimal
